// ImpactReport — single source of truth for the analysis schema.
// Imported by both server (validation, prompts) and web (rendering).

export type SeverityBand = 'minimal' | 'moderate' | 'high' | 'severe' | 'critical';
export type ImpactDirection = 'negative' | 'positive' | 'mixed';

export type DocumentType =
  | 'short_seller'
  | 'investigative'
  | 'regulatory'
  | 'press_release'
  | 'news'
  | 'other';

export type DimensionKey =
  | 'market'
  | 'reputational'
  | 'legal'
  | 'financial'
  | 'operational'
  | 'sentiment';

export interface DimensionScore {
  key: DimensionKey;
  label: string;
  score: number; // 0-100
  direction: ImpactDirection;
  confidence: number; // 0-1
  rationale: string;
}

export interface EntityImpact {
  name: string;
  kind: 'company' | 'person' | 'sector' | 'other';
  score: number; // 0-100
  ticker?: string;
  summary: string;
}

export type ClaimSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface Claim {
  text: string;
  severity: ClaimSeverity;
  pageRef: string; // e.g. "p. 12" or "pp. 3-5"
}

export interface HistoricalAnalog {
  event: string;
  year: number;
  outcome: string;
  similarity: number; // 0-1
}

export interface ImpactReport {
  meta: {
    id: string;
    analyzedAt: string; // ISO
    model: string;
    sourceFile: string;
  };
  document: {
    title: string;
    publisher: string;
    publishDate: string | null;
    documentType: DocumentType;
    subjectEntities: string[];
    disclosedConflicts: string[];
  };
  overall: {
    score: number; // 0-100
    band: SeverityBand;
    direction: ImpactDirection;
    summary: string;
  };
  dimensions: DimensionScore[];
  entities: EntityImpact[];
  claims: Claim[];
  timeline: {
    immediate: string;
    shortTerm: string;
    longTerm: string;
  };
  analogs: HistoricalAnalog[];
  risks: string[];
  credibility: {
    score: number; // 0-100
    rationale: string;
  };
  disclaimer: string;
}

// ---- API / job types ----

export type JobStep =
  | 'guard'
  | 'document'
  | 'scoring'
  | 'projections'
  | 'synthesis'
  | 'validate';

export const JOB_STEPS: { key: JobStep; label: string }[] = [
  { key: 'guard', label: 'Checking scope & guardrails' },
  { key: 'document', label: 'Reading the document' },
  { key: 'scoring', label: 'Scoring impact dimensions' },
  { key: 'projections', label: 'Projecting timeline & finding analogs' },
  { key: 'synthesis', label: 'Writing executive synthesis' },
  { key: 'validate', label: 'Validating & finalizing' },
];

export type AnalysisStatus =
  | 'uploaded'
  | 'analyzing'
  | 'complete'
  | 'rejected'
  | 'error';

export interface ReportRecord {
  id: string;
  fileName: string;
  fileSize: number;
  pageCount: number | null;
  instructions: string;
  typeHint: string;
  status: AnalysisStatus;
  createdAt: string;
  rejectionReason?: string;
  errorMessage?: string;
  result?: ImpactReport;
}

// SSE events emitted by GET /api/reports/:id/stream
export type StreamEvent =
  | { type: 'step'; step: JobStep; state: 'start' | 'done'; note?: string }
  | { type: 'partial'; entities?: string[]; claims?: string[] }
  | { type: 'rejected'; reason: string }
  | { type: 'error'; message: string }
  | { type: 'complete'; reportId: string };

export function bandForScore(score: number): SeverityBand {
  if (score >= 85) return 'critical';
  if (score >= 70) return 'severe';
  if (score >= 50) return 'high';
  if (score >= 30) return 'moderate';
  return 'minimal';
}

export const BAND_LABELS: Record<SeverityBand, string> = {
  minimal: 'Minimal',
  moderate: 'Moderate',
  high: 'High',
  severe: 'Severe',
  critical: 'Critical',
};

export const DISCLAIMER =
  'This report was generated by an AI system for informational purposes only. It is not investment, legal, or financial advice. All claims referenced are allegations made by the source document and are attributed to its publisher; they are not assertions of fact by this system. Verify independently before acting on any information herein.';
